#debug: true
logging:
  level:
    root: INFO
    demo: DEBUG


server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: always


spring:
  application:
    name: springboot-demo

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 2000
      database: 0
      lettuce:
        max-active: 8
        max-idle: 8
        min-idle: 0
        timeout: 2000


app:
  redis:
    loadBatchSize: 100
    expirationSeconds:
      default: 300
      filmText: 5


datasource:
  app:
    jdbc-url: ${BASE_JDBC_URL}/world
    username: ${APP_DB_USERNAME}
    password: ${APP_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    pool-name: appHikariCP
    maximum-pool-size: 10
    minimum-idle: 5
    connection-timeout: 30000
    connection-test-query: SELECT 1

  world:
    jdbc-url: ${BASE_JDBC_URL}/world
    username: ${WORLD_DB_USERNAME}
    password: ${WORLD_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    pool-name: worldHikariCP
    maximum-pool-size: 10
    minimum-idle: 5
    connection-timeout: 30000
    connection-test-query: SELECT 1

  sakila:
    jdbc-url: ${BASE_JDBC_URL}/sakila
    username: ${SAKILA_DB_USERNAME}
    password: ${SAKILA_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    pool-name: sailaHikariCP
    maximum-pool-size: 10
    minimum-idle: 5
    connection-timeout: 30000
    connection-test-query: SELECT 1