#debug: true
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{36}] %msg%n"
  level:
#    root: DEBUG
    demo: DEBUG


server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: always


spring:
  application:
    name: springboot-demo

  profiles:
    active: dev-group # can be activated from env variable SPRING_PROFILES_ACTIVE
    group:
      dev-group: dev,datasource,redis # Defines what profiles are included in "dev-group"
      uat-group: uat,datasource,redis

  cloud:
    config:
      fail-fast: true
      label: main
  config:
    import:
      - configserver:${CONFIG_SERVER_HOSTNAME:http://localhost}:${CONFIG_SERVER_PORT:8888}


management:
  endpoints:
    web:
      exposure:
        include: health,refresh,info
  endpoint:
    health:
      show-details: always
