#debug: true
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{36}] %msg%n"
  level:
#    root: DEBUG
    demo: DEBUG


server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: always


spring:
  application:
    name: springboot-demo

  profiles:
#    active: dev_group # activated from env variable SPRING_PROFILES_ACTIVE
    group:
      dev_group: dev,datasource,redis # Defines what profiles are included in "dev_group"
      uat_group: uat,datasource,redis

  cloud:
    config:
      fail-fast: true
      label: main
  config:
    import:
      - configserver:http://localhost:8888


management:
  endpoints:
    web:
      exposure:
        include: health,refresh,info
  endpoint:
    health:
      show-details: always
