apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "springboot-demo-chart.fullname" . }}-configmap
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: ""

data:
  APP_VERSION: {{ .Chart.AppVersion | quote }}
  BASE_JDBC_URL: {{ .Values.config.jdbc.baseUrl | quote }}
  APP_DB_USERNAME: {{ .Values.config.jdbc.usernames.app | quote }}
  WORLD_DB_USERNAME: {{ .Values.config.jdbc.usernames.world | quote }}
  SAKILA_DB_USERNAME: {{ .Values.config.jdbc.usernames.sakila | quote }}
  REDIS_HOST: {{ .Values.config.redis.host | quote }}
  REDIS_PORT: {{ .Values.config.redis.port | quote }}
