apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "springboot-demo-chart.fullname" . }}-configmap
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: ""

data:
  APP_VERSION: {{ .Chart.AppVersion | quote }}
  APP_HOSTNAME: {{ .Values.config.app.hostname | quote }}
  APP_PORT: {{ .Values.config.app.port | quote }}
  CONFIG_SERVER_HOSTNAME: {{ .Values.config.configServer.hostname | quote }}
  CONFIG_SERVER_PORT: {{ .Values.config.configServer.port | quote }}
