{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "springboot-demo-chart.fullname" . }}-hpa
  labels:
    {{- include "springboot-demo-chart.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "springboot-demo-chart.fullname" . }}-deploy
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization # Utilization | AverageValue
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }} # Target percentage (e.g., 50% CPU usage)
          #averageValue: 500m      # Target absolute value (e.g., 500 milli-cores)
    {{- end }}
    {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization # Utilization | AverageValue
          averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }} # Target percentage (e.g., 50% memory usage)
    {{- end }}
#    - type: Pods
#      pods:
#        metric:
#          name: requests_per_second # need Prometheus
#        target:
#          type: AverageValue
#          averageValue: 1k
    {{- if .Values.autoscaling.behavior }}
    behavior:
      {{- toYaml .Values.autoscaling.behavior | nindent 2 }}
    {{- end }}
{{- end }}
