apiVersion: v1
kind: Service
metadata:
  name: {{ include "springboot-demo-chart.fullname" . }}-service
  labels:
    {{- include "springboot-demo-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "springboot-demo-chart.selectorLabels" . | nindent 4 }}
