apiVersion: apps/v1
kind: Deployment

metadata:
  name: springboot-demo-deploy
  labels:
    app: springboot-demo-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-demo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: springboot-demo
    spec:
      containers:
      - name: springboot-demo-container
        image: springboot-demo:v1.0.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: "500Mi"
        envFrom:
        - configMapRef:
            name: springboot-demo-configmap
        - secretRef:
            name: springboot-demo-secret