apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: springboot-demo-hpa

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: springboot-demo-deploy
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 10
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 5
      policies:
      - type: Pods
        value: 1
    scaleUp:
      stabilizationWindowSeconds: 5
      policies:
      - type: Pods
        value: 1