apiVersion: v1
kind: Service

metadata:
  name: springboot-demo-service

spec:
  type: NodePort
  selector:
    app: springboot-demo
  ports:
    - name: http-web # custom name
      protocol: TCP # Optional (default is TCP)
      port: 80 # service port, can be accessed inside the K8s cluster
      targetPort: 8080 # container port
      nodePort: 30000 # can be accessed outside the K8s cluster