apiVersion: v1
kind: Service

metadata:
  name: springboot-demo-service

spec:
  selector:
    app: springboot-demo
  ports:
    - protocol: TCP
      port: 80 # service port, can be accessed outside pod
      targetPort: 8080 # container port
  type: NodePort